spring:
  application:
    name: todo
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: "1004guswjd"
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.todo
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
